import type { MaterialItem } from "./proposal-templates";

/** System defaults for Roofing — Good package (IKO). */
export const defaultRoofingGoodTierMaterialsTable: MaterialItem[] = [
  {
    id: "roof-iko-shingles",
    category: "Shingles",
    product: "Cambridge Architectural Shingles",
    brand: "IKO",
    warranty: "Limited Lifetime",
    notes: "Dimensional architectural shingles",
  },
  {
    id: "roof-iko-starter",
    category: "Starter Strip",
    product: "Leading Edge Plus Starter",
    brand: "IKO",
    warranty: "Limited",
    notes: "Starter protection for eaves and rakes",
  },
  {
    id: "roof-iko-ridge",
    category: "Ridge Cap",
    product: "Hip & Ridge 12",
    brand: "IKO",
    warranty: "Limited Lifetime",
    notes: "Matching ridge cap system",
  },
  {
    id: "roof-iko-underlay",
    category: "Underlayment",
    product: "RoofGard-Cool Grey Synthetic",
    brand: "IKO",
    warranty: "Limited Lifetime",
    notes: "Synthetic roof deck protection",
  },
  {
    id: "roof-iko-ice",
    category: "Ice & Water Shield",
    product: "GoldShield Ice & Water Protector",
    brand: "IKO",
    warranty: "Manufacturer Specs",
    notes: "Waterproof membrane at vulnerable areas",
  },
  {
    id: "roof-iko-drip",
    category: "Drip Edge",
    product: "Aluminum Drip Edge",
    brand: "Standard",
    warranty: "N/A",
    notes: "Installed at roof perimeter",
  },
  {
    id: "roof-iko-pipe",
    category: "Pipe Boots",
    product: "Rubber Pipe Flashing",
    brand: "Oatey",
    warranty: "N/A",
    notes: "Standard plumbing vent flashing",
  },
  {
    id: "roof-iko-vent",
    category: "Ventilation",
    product: "Static Roof Vent",
    brand: "Standard",
    warranty: "N/A",
    notes: "Standard attic ventilation",
  },
  {
    id: "roof-iko-nails",
    category: "Nails",
    product: "Roofing Coil Nails",
    brand: "Grip-Rite",
    warranty: "N/A",
    notes: "Code-compliant fastening system",
  },
];

/** System defaults for Roofing — Better package (GAF Premium). */
export const defaultRoofingBetterTierMaterialsTable: MaterialItem[] = [
  {
    id: "roof-gaf-shingles",
    category: "Shingles",
    product: "Timberline HDZ",
    brand: "GAF",
    warranty: "Limited Lifetime",
    notes: "High-definition architectural shingles",
  },
  {
    id: "roof-gaf-starter",
    category: "Starter Strip",
    product: "Pro-Start Starter Strip",
    brand: "GAF",
    warranty: "Lifetime",
    notes: "Enhanced wind uplift protection",
  },
  {
    id: "roof-gaf-ridge",
    category: "Ridge Cap",
    product: "Seal-A-Ridge",
    brand: "GAF",
    warranty: "Limited Lifetime",
    notes: "Matching dimensional ridge cap",
  },
  {
    id: "roof-gaf-underlay",
    category: "Underlayment",
    product: "FeltBuster Synthetic Felt",
    brand: "GAF",
    warranty: "Limited Lifetime",
    notes: "Durable synthetic underlayment",
  },
  {
    id: "roof-gaf-ice",
    category: "Ice & Water Shield",
    product: "WeatherWatch Leak Barrier",
    brand: "GAF",
    warranty: "Manufacturer Specs",
    notes: "Self-adhered leak protection membrane",
  },
  {
    id: "roof-gaf-drip",
    category: "Drip Edge",
    product: "26-Gauge Drip Edge",
    brand: "Premium",
    warranty: "N/A",
    notes: "Heavy-duty edge flashing",
  },
  {
    id: "roof-gaf-pipe",
    category: "Pipe Boots",
    product: "No-Calk Lead Pipe Boots",
    brand: "Oatey",
    warranty: "N/A",
    notes: "Long-lasting lead flashing",
  },
  {
    id: "roof-gaf-vent",
    category: "Ventilation",
    product: "Cobra Ridge Vent",
    brand: "GAF",
    warranty: "Limited",
    notes: "Balanced attic ventilation system",
  },
  {
    id: "roof-gaf-nails",
    category: "Nails",
    product: "Ring-Shank Roofing Nails",
    brand: "Grip-Rite",
    warranty: "N/A",
    notes: "Increased holding power",
  },
  {
    id: "roof-gaf-warranty-up",
    category: "Warranty Upgrade",
    product: "System Plus Warranty",
    brand: "GAF",
    warranty: "50-Year Coverage",
    notes: "Enhanced manufacturer-backed protection",
  },
];

/** System defaults for Roofing — Best package (Owens Corning). */
export const defaultRoofingBestTierMaterialsTable: MaterialItem[] = [
  {
    id: "roof-oc-shingles",
    category: "Shingles",
    product: "Duration FLEX",
    brand: "Owens Corning",
    warranty: "Limited Lifetime",
    notes: "SBS modified impact-resistant shingles",
  },
  {
    id: "roof-oc-starter",
    category: "Starter Strip",
    product: "Starter Strip Plus",
    brand: "Owens Corning",
    warranty: "Lifetime",
    notes: "Premium starter protection",
  },
  {
    id: "roof-oc-ridge",
    category: "Ridge Cap",
    product: "ProEdge FLEX Hip & Ridge",
    brand: "Owens Corning",
    warranty: "Lifetime",
    notes: "Impact-resistant ridge system",
  },
  {
    id: "roof-oc-underlay",
    category: "Underlayment",
    product: "Deck Defense Synthetic Underlayment",
    brand: "Owens Corning",
    warranty: "Lifetime",
    notes: "Premium synthetic deck protection",
  },
  {
    id: "roof-oc-ice",
    category: "Ice & Water Shield",
    product: "WeatherLock Flex Flexible Seal",
    brand: "Owens Corning",
    warranty: "Lifetime",
    notes: "Advanced waterproof membrane",
  },
  {
    id: "roof-oc-drip",
    category: "Drip Edge",
    product: "Heavy Gauge Drip Edge",
    brand: "Premium",
    warranty: "N/A",
    notes: "Enhanced perimeter durability",
  },
  {
    id: "roof-oc-pipe",
    category: "Pipe Boots",
    product: "Lead Flashing Boots",
    brand: "Lifetime Tool",
    warranty: "N/A",
    notes: "Premium long-term flashing",
  },
  {
    id: "roof-oc-vent",
    category: "Ventilation",
    product: "VentSure Ridge Vent System",
    brand: "Owens Corning",
    warranty: "Limited Lifetime",
    notes: "Optimized attic airflow",
  },
  {
    id: "roof-oc-nails",
    category: "Nails",
    product: "Hot-Dipped Ring-Shank Nails",
    brand: "Grip-Rite",
    warranty: "N/A",
    notes: "Superior fastening system",
  },
  {
    id: "roof-oc-warranty-up",
    category: "Warranty Upgrade",
    product: "Platinum Protection Warranty",
    brand: "Owens Corning",
    warranty: "Workmanship Coverage",
    notes: "Premium manufacturer-backed warranty",
  },
  {
    id: "roof-oc-impact",
    category: "Impact Resistance",
    product: "Class 4 Impact Resistant System",
    brand: "Owens Corning",
    warranty: "Lifetime",
    notes: "Better hail resistance",
  },
  {
    id: "roof-oc-wind",
    category: "Wind Protection",
    product: "High Wind Roofing System",
    brand: "Owens Corning",
    warranty: "130 MPH",
    notes: "Enhanced wind warranty",
  },
];
