import type { TierProduct } from "./app-data";

// Default roofing product catalog imported from roofle_catalog_images.xlsx.
export const defaultRoofleCatalogProducts = [
  {
    "id": "89a38d72-aedb-5dd5-80ac-815b25218758",
    "trade": "Roofing",
    "tier": "Better",
    "productId": "duration",
    "productName": "TruDefinition® Duration® Shingles",
    "productType": "Asphalt Shingle",
    "description": "SureNail® Technology, StreakGuard® Algae Resistance Technology³, Wind Resistance, and Class 3 Impact Resistance⁶.",
    "productBrand": "Owens Corning",
    "productLine": "Duration",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://imagecdn.owenscorning.com/ocimages/image/upload/c_crop,h_3699,w_3699,x_20,y_20/c_scale,w_768/f_auto,q_auto/v1/pagebuilder/uploads/prod/11009665/TDD_Brownwood_RGB_swatch_lg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/owens-corning/duration/williamsburggray"
  },
  {
    "id": "a37011e3-b84e-5d90-97b2-5a77fa2a06d7",
    "trade": "Roofing",
    "tier": "Better",
    "productId": "duration-designer",
    "productName": "TruDefinition® Duration® Designer Shingles",
    "productType": "Asphalt Shingle",
    "description": "Offers spectacular curb appeal with bright, bold and brilliant colors with the TruDefinition® color platform along with high performance with SureNail® Technology and Streakguard Algae Resistance Technology.³",
    "productBrand": "Owens Corning",
    "productLine": "Duration Designer",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://imagecdn.owenscorning.com/ocimages/image/upload/c_crop,h_3699,w_3699,x_200,y_0/c_scale,w_768/f_auto,q_auto/v1/pagebuilder/uploads/prod/11262130/TDD_Teak_RGB_swatch_lg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/owens-corning/duration-designer/summerharvest"
  },
  {
    "id": "ae4e31e9-4a3a-5525-9d3c-7898a8b801bf",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "duration-flex",
    "productName": "TruDefinition® Duration® FLEX® Shingles",
    "productType": "Asphalt Shingle",
    "description": "The rubberizing effect of SBS Modified Asphalt makes the shingle pliable and gives them greater flexibility and enhanced durability and toughness. Includes Class 4 Impact Resistance¹, SureNail® Technology, Premium Colors, TruDefinition® color platform, and Streakguard Algae Resistance Technology.³",
    "productBrand": "Owens Corning",
    "productLine": "Duration FLEX",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://imagecdn.owenscorning.com/ocimages/image/upload/c_crop,h_3699,w_3699,x_300,y_15/c_scale,w_768/f_auto,q_auto/v1/pagebuilder/uploads/prod/12206780/DSDP_BlackSable_RGB_swatch_lg_07-2022",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/owens-corning/duration-flex/driftwood"
  },
  {
    "id": "15478004-3d77-5b63-afa4-844af4661289",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "duration-storm",
    "productName": "TruDefinition® Duration® STORM® Shingles",
    "productType": "Asphalt Shingle",
    "description": "Non-SBS, UL2218 and FM 4473 Class 4 Impact Resistance¹ shingles with patented WeatherGuard® Technology, TruDefinition® color platform, and SureNail® Technology.",
    "productBrand": "Owens Corning",
    "productLine": "Duration STORM",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://imagecdn.owenscorning.com/ocimages/image/upload/c_crop,h_3699,w_3699,x_20,y_20/c_scale,w_768/f_auto,q_auto/v1/pagebuilder/uploads/prod/11132163/TDD_Driftwood_RGB_swatch_lg_06-2022",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Designer | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/owens-corning/duration-storm/driftwood"
  },
  {
    "id": "bc8e0f20-dc7e-53af-9845-3f3bd7c312dd",
    "trade": "Roofing",
    "tier": "Better",
    "productId": "oakridge",
    "productName": "Oakridge® Shingles",
    "productType": "Asphalt Shingle",
    "description": "A step-up from 3-tab shingles, these striking architectural shingle offer premium protection and impressive curb appeal with a full double layer protection in the nailing zone.",
    "productBrand": "Owens Corning",
    "productLine": "Oakridge",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://imagecdn.owenscorning.com/ocimages/image/upload/c_crop,h_3699,w_3699,x_1050,y_630/c_scale,w_768/f_auto,q_auto/v1/pagebuilder/uploads/prod/11340691/TDD_EstateGray_RGB_swatch_lg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 110 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/owens-corning/oakridge/driftwood"
  },
  {
    "id": "c0b9680c-b19d-5201-adfd-2550a64bd211",
    "trade": "Roofing",
    "tier": "Better",
    "productId": "duration-max",
    "productName": "TruDefinition® Duration® MAX® Shingles",
    "productType": "Asphalt Shingle",
    "description": "A thick, high-profile appearance of a wood shingle with enhanced durability with Class 3 Impact Resistance⁶, bold TruDefinition® color platform, and SureNail® Technology",
    "productBrand": "Owens Corning",
    "productLine": "Duration MAX",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://imagecdn.owenscorning.com/ocimages/image/upload/c_crop,h_3699,w_3699,x_700,y_15/c_scale,w_768/f_auto,q_auto/v1/pagebuilder/uploads/prod/11340684/TDD_OnyxBlack_RGB_swatch_lg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/owens-corning/duration-max/summerwood"
  },
  {
    "id": "0117ad68-5fe6-5a8b-a8cd-9de2979ce65e",
    "trade": "Roofing",
    "tier": "Better",
    "productId": "trudefinition-duration-shingles-designer-colors",
    "productName": "TruDefinition® Duration® Shingles + Designer Colors",
    "productType": "Asphalt Shingle",
    "description": "SureNail® Technology, StreakGuard® Algae Resistance Technology³, Wind Resistance, and Class 3 Impact Resistance⁶",
    "productBrand": "Owens Corning",
    "productLine": "Duration Designer Colors",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://imagecdn.owenscorning.com/ocimages/image/upload/c_crop,h_3699,w_3699,x_200,y_0/c_scale,w_768/f_auto,q_auto/v1/pagebuilder/uploads/prod/11262130/TDD_Teak_RGB_swatch_lg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/owens-corning/trudefinition-duration-shingles-designer-colors/williamsburggray"
  },
  {
    "id": "0c64503c-abd4-5a82-9c1c-febe323dbe06",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "woodcrest",
    "productName": "Woodcrest® Shingles",
    "productType": "Asphalt Shingle",
    "description": "Thick maintenance-free architectural shingles with a natural, rustic look resembling wood shake with Streakguard® Algae Resistance Protection³",
    "productBrand": "Owens Corning",
    "productLine": "Woodcrest",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://imagecdn.owenscorning.com/ocimages/image/upload/c_crop,h_3699,w_3699,x_20,y_20/c_scale,w_768/f_auto,q_auto/v1/pagebuilder/uploads/prod/11132163/TDD_Driftwood_RGB_swatch_lg_06-2022",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Designer | Wind rating: 110 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/owens-corning/woodcrest/summerwood"
  },
  {
    "id": "e8d77c8a-74bb-532a-90e2-6fe43b14dc20",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "woodmoor",
    "productName": "Woodmoor® Shingles",
    "productType": "Asphalt Shingle",
    "description": "Bold, dimensional design, High durability and performance, Color variety with rich tone depth",
    "productBrand": "Owens Corning",
    "productLine": "Woodmoor",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://imagecdn.owenscorning.com/ocimages/image/upload/c_crop,h_3699,w_3699,x_700,y_15/c_scale,w_768/f_auto,q_auto/v1/pagebuilder/uploads/prod/11340684/TDD_OnyxBlack_RGB_swatch_lg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Designer | Wind rating: 110 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/owens-corning/woodmoor/carbon"
  },
  {
    "id": "a9f519e1-6dfe-5e3a-83de-d0fd58f230f5",
    "trade": "Roofing",
    "tier": "Better",
    "productId": "duration-premium",
    "productName": "Duration® Premium Shingles",
    "productType": "Asphalt Shingle",
    "description": "Offers the advanced performance of SureNail® Technology, Triple Layer Protection®, Wind Resistant, and Class 3 Impact Resistance⁶",
    "productBrand": "Owens Corning",
    "productLine": "Duration Premium",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://imagecdn.owenscorning.com/ocimages/image/upload/c_crop,h_3699,w_3699,x_20,y_20/c_scale,w_768/f_auto,q_auto/v1/pagebuilder/uploads/prod/11009665/TDD_Brownwood_RGB_swatch_lg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/owens-corning/duration-premium/driftwood"
  },
  {
    "id": "44cf4e39-ba6f-51fb-8177-f3f105b38eb9",
    "trade": "Roofing",
    "tier": "Better",
    "productId": "duration-cool",
    "productName": "TruDefinition® Duration® COOL Shingles",
    "productType": "Asphalt Shingle",
    "description": "Rich shingle colors, solar-reflecting granules and SureNail® Technology meet Cool Roof requirements",
    "productBrand": "Owens Corning",
    "productLine": "Duration COOL",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://imagecdn.owenscorning.com/ocimages/image/upload/c_crop,h_3699,w_3699,x_20,y_20/c_scale,w_768/f_auto,q_auto/v1/pagebuilder/uploads/prod/11132163/TDD_Driftwood_RGB_swatch_lg_06-2022",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/owens-corning/duration-cool/summerwood"
  },
  {
    "id": "12b73f93-9b6c-5d4e-9622-aa54f482d3ce",
    "trade": "Roofing",
    "tier": "Better",
    "productId": "duration-cool-plus",
    "productName": "Duration® COOL Plus Shingles",
    "productType": "Asphalt Shingle",
    "description": "Beautifully rich shingle colors with solar-reflecting granules to meet 20+ SRI. Includes TruDefinition® color platform, Class 3 Impact Resistance⁶, and SureNail® Technology.",
    "productBrand": "Owens Corning",
    "productLine": "Duration COOL Plus",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://imagecdn.owenscorning.com/ocimages/image/upload/c_crop,h_3699,w_3699,x_1050,y_630/c_scale,w_768/f_auto,q_auto/v1/pagebuilder/uploads/prod/11340691/TDD_EstateGray_RGB_swatch_lg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/owens-corning/duration-cool-plus/rollingstone"
  },
  {
    "id": "9367f82a-712f-5c8d-b2a6-ef14b1df3f8f",
    "trade": "Roofing",
    "tier": "Good",
    "productId": "atticat-pink-blown-in-insulation",
    "productName": "AttiCat® PINK® Blown-In Insulation",
    "productType": "Synthetic",
    "description": "Energy savings, Easy & Fast Installation, Mold/Moisture/Fire Resistant",
    "productBrand": "Owens Corning",
    "productLine": "AttiCat",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://imagecdn.owenscorning.com/ocimages/image/upload/c_crop,h_3699,w_3699,x_20,y_20/c_scale,w_768/f_auto,q_auto/v1/pagebuilder/uploads/prod/11009665/TDD_Brownwood_RGB_swatch_lg",
    "warrantyYears": 0,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Specialty | Wind rating: N/A | Fire rating: N/A | Roofle URL: https://catalog.roofle.com/catalog/owens-corning/atticat-pink-blown-in-insulation/pink"
  },
  {
    "id": "5c12d489-e410-5721-8370-f8a27947a4e1",
    "trade": "Roofing",
    "tier": "Good",
    "productId": "deckseal",
    "productName": "DeckSeal™ Shingles",
    "productType": "Asphalt Shingle",
    "description": "Self-Adhered Technology, Easy Installation, Exceptional Durability, Weather Resistance, Energy Efficiency",
    "productBrand": "Owens Corning",
    "productLine": "DeckSeal",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://imagecdn.owenscorning.com/ocimages/image/upload/c_crop,h_3699,w_3699,x_20,y_20/c_scale,w_768/f_auto,q_auto/v1/pagebuilder/uploads/prod/11132163/TDD_Driftwood_RGB_swatch_lg_06-2022",
    "warrantyYears": 15,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Specialty | Wind rating: N/A | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/owens-corning/deckseal/estategray"
  },
  {
    "id": "138f2cd4-97ee-5561-acbd-c9cfdf1f6552",
    "trade": "Roofing",
    "tier": "Better",
    "productId": "timberline-hdz",
    "productName": "Timberline HDZ Shingles",
    "productType": "Asphalt Shingle",
    "description": "North America's #1 selling shingle plus enhanced performance. LayerLock™ technology, StainGuard Plus™ algae protection.",
    "productBrand": "GAF",
    "productLine": "Timberline HDZ",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://product-assets.gaf.com/media/catalog/product/t/i/timberline-hdz-pewter_gray.png?width=660",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/gaf/timberline-hdz/weatheredwood"
  },
  {
    "id": "2aace49b-b174-5b48-a6e5-c0225f270f66",
    "trade": "Roofing",
    "tier": "Better",
    "productId": "timberline-armorshield-ii",
    "productName": "Timberline Armorshield II Shingles",
    "productType": "Asphalt Shingle",
    "description": "Advanced impact resistance with striking look. Class 4 impact resistance.",
    "productBrand": "GAF",
    "productLine": "Timberline Armorshield II",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://product-assets.gaf.com/media/catalog/product/_/0/_0016_timberlinehdz_copper-canyon.png",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/gaf/timberline-armorshield-ii/weatheredwood"
  },
  {
    "id": "7199bf13-6c1d-5356-b1d8-36347a4e9405",
    "trade": "Roofing",
    "tier": "Better",
    "productId": "timberline-american-harvest",
    "productName": "Timberline American Harvest Shingles",
    "productType": "Asphalt Shingle",
    "description": "High-performing shingle with custom design color palette for unique curb appeal.",
    "productBrand": "GAF",
    "productLine": "Timberline American Harvest",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://product-assets.gaf.com/media/catalog/product/_/0/_0016_timberlinehdz_copper-canyon.png",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/gaf/timberline-american-harvest/goldenharvest"
  },
  {
    "id": "3438675d-bc60-5853-8839-848dadaf19ba",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "timberline-uhdz",
    "productName": "Timberline® UHDZ™ Shingles",
    "productType": "Asphalt Shingle",
    "description": "Ultra-Dimensional Design, Exceptional Durability, Vibrant Color Options, Enhanced Curb Appeal with ultra-high definition.",
    "productBrand": "GAF",
    "productLine": "Timberline UHDZ",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://product-assets.gaf.com/media/catalog/product/t/i/timberline-uhdz-charcoal.png",
    "warrantyYears": 0,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/gaf/timberline-uhdz/charcoal"
  },
  {
    "id": "f483855b-7bb4-5b26-aa05-cde8f2e0504d",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "camelot-ii",
    "productName": "Camelot II Shingles",
    "productType": "Asphalt Shingle",
    "description": "Designer slate look with custom color palette. Premium luxury architectural shingles.",
    "productBrand": "GAF",
    "productLine": "Camelot II",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://product-assets.gaf.com/media/catalog/product/c/a/camelot-ii-weathered-timber.png",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Designer | Wind rating: 110 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/gaf/camelot-ii/weatheredtimber"
  },
  {
    "id": "8666ceb1-86e4-54a3-8f55-6fb40d246533",
    "trade": "Roofing",
    "tier": "Good",
    "productId": "liberty-roll",
    "productName": "Liberty Roll Shingles",
    "productType": "Asphalt Shingle",
    "description": "Easy Installation, Durability, Weather Resistance, Versatility, Energy Efficiency. Low-slope roofing solution.",
    "productBrand": "GAF",
    "productLine": "Liberty Roll",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://product-assets.gaf.com/media/catalog/product/l/i/liberty-roll-black.png",
    "warrantyYears": 15,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Specialty | Wind rating: N/A | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/gaf/liberty-roll/black"
  },
  {
    "id": "8ed4b073-e7dc-577b-a4e8-62d6b88fac9b",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "grand-sequoia",
    "productName": "Grand Sequoia Shingles",
    "productType": "Asphalt Shingle",
    "description": "Affordable luxury with artisanal character. Designer wood-shake look.",
    "productBrand": "GAF",
    "productLine": "Grand Sequoia",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://product-assets.gaf.com/media/catalog/product/g/r/grand-sequoia-weathered-wood.png",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Designer | Wind rating: 110 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/gaf/grand-sequoia/weatheredwood"
  },
  {
    "id": "0d6b7b0f-e0f0-5b87-be4c-e4ad1f5dc830",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "grand-sequoia-armorshield",
    "productName": "Grand Sequoia Armorshield Shingles",
    "productType": "Asphalt Shingle",
    "description": "Advanced impact resistance with affordable luxury. Class 4 impact-rated designer shingle.",
    "productBrand": "GAF",
    "productLine": "Grand Sequoia Armorshield",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://product-assets.gaf.com/media/catalog/product/g/r/grand-sequoia-weathered-wood.png",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Designer | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/gaf/grand-sequoia-armorshield/weatheredwood"
  },
  {
    "id": "013692aa-e9fd-5030-a436-163a2744ea2c",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "slateline",
    "productName": "Slateline Shingles",
    "productType": "Asphalt Shingle",
    "description": "Designer slate look with GAF Advanced Protection technology. Premium dimensional appearance.",
    "productBrand": "GAF",
    "productLine": "Slateline",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://product-assets.gaf.com/media/catalog/product/s/l/slateline-weathered-slate.png",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Designer | Wind rating: 110 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/gaf/slateline/weatheredslate"
  },
  {
    "id": "a4c7b0ca-0d29-5411-8a90-23cc3bbdffc5",
    "trade": "Roofing",
    "tier": "Good",
    "productId": "royal-sovereign",
    "productName": "Royal Sovereign® Shingles",
    "productType": "Asphalt Shingle",
    "description": "Superior Durability, Timeless Elegance, Reliable Weather Resistance, Meticulous Craftsmanship. Classic 3-tab shingle.",
    "productBrand": "GAF",
    "productLine": "Royal Sovereign",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://product-assets.gaf.com/media/catalog/product/r/o/royal-sovereign-charcoal.png",
    "warrantyYears": 25,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: 3-Tab | Wind rating: 60 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/gaf/royal-sovereign/charcoal"
  },
  {
    "id": "2a94fb30-0213-5d86-b126-9f1cd426503e",
    "trade": "Roofing",
    "tier": "Better",
    "productId": "timberline-hdz-reflector-series",
    "productName": "Timberline HDZ Reflector Series Shingles",
    "productType": "Asphalt Shingle",
    "description": "Cool roof performance with solar-reflecting granules. ENERGY STAR® rated.",
    "productBrand": "GAF",
    "productLine": "Timberline HDZ Reflector",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://product-assets.gaf.com/media/catalog/product/t/i/timberline-hdz-rs-charcoal.png",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/gaf/timberline-hdz-reflector-series/agedchestnut"
  },
  {
    "id": "e4d74dcc-afae-5042-8975-285e616e6f01",
    "trade": "Roofing",
    "tier": "Better",
    "productId": "timberline-cool-series",
    "productName": "Timberline Cool Series Shingles",
    "productType": "Asphalt Shingle",
    "description": "Cool roof performance with solar-reflecting granules for energy efficiency.",
    "productBrand": "GAF",
    "productLine": "Timberline Cool Series",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://product-assets.gaf.com/media/catalog/product/t/i/timberline-cool-series-white.png",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/gaf/timberline-cool-series/weatheredwood"
  },
  {
    "id": "d3c0ec20-2f70-537c-8731-33771f260509",
    "trade": "Roofing",
    "tier": "Better",
    "productId": "dynasty",
    "productName": "Dynasty Performance Shingles",
    "productType": "Asphalt Shingle",
    "description": "Performance shingles with ArmourZone reinforcement technology. Extra tear resistance, 130 MPH wind rating. Bold high-contrast colors. 15-year algae warranty.",
    "productBrand": "IKO",
    "productLine": "Dynasty",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.iko.com/na/wp-content/uploads/2024/05/RGB-0186_IKO_NRDC_SHGL_HOME_FRGY_DJI_0186.webp",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/iko/dynasty"
  },
  {
    "id": "81844a44-0a84-5d16-abc4-9152a251da08",
    "trade": "Roofing",
    "tier": "Good",
    "productId": "cambridge",
    "productName": "Cambridge Architectural Shingles",
    "productType": "Asphalt Shingle",
    "description": "IKO's most popular architectural shingle. Large, true-to-size shingles for full coverage. 15 hi-def colors. Wind warranty 110 MPH (upgradeable to 130 MPH). 10-year algae resistance.",
    "productBrand": "IKO",
    "productLine": "Cambridge",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.iko.com/na/wp-content/uploads/2024/05/cambridge-laminated-shingle.webp",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/iko/cambridge"
  },
  {
    "id": "b3622c9d-aa36-5b48-95f1-04c6f95db6bd",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "armourshake",
    "productName": "Armourshake Designer Shingles",
    "productType": "Asphalt Shingle",
    "description": "Premium heavyweight shingles replicate the look of natural wood shakes with enhanced durability and weather protection.",
    "productBrand": "IKO",
    "productLine": "Armourshake",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.iko.com/na/wp-content/uploads/2024/05/armourshake-designer-shingle.webp",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Designer | Wind rating: 110 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/iko/armourshake"
  },
  {
    "id": "7f5efa9d-90a3-5544-b22f-5f4476cf8b95",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "royal-estate",
    "productName": "Royal Estate Designer Shingles",
    "productType": "Asphalt Shingle",
    "description": "Estate-style luxury shingles with deep shadow lines and rich color blends for premium curb appeal.",
    "productBrand": "IKO",
    "productLine": "Royal Estate",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.iko.com/na/wp-content/uploads/2024/05/royal-estate-designer-shingle.webp",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Designer | Wind rating: 110 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/iko/royal-estate"
  },
  {
    "id": "586b06ae-3be7-5971-9791-60a28be1b69e",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "crown-slate",
    "productName": "Crown Slate Designer Shingles",
    "productType": "Asphalt Shingle",
    "description": "Premium slate-look shingles with deep shadow lines and rich color dimension for luxury homes.",
    "productBrand": "IKO",
    "productLine": "Crown Slate",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.iko.com/na/wp-content/uploads/2024/05/crowne-slate-designer-shingle.webp",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Designer | Wind rating: 110 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/iko/crown-slate"
  },
  {
    "id": "01d63078-d2e0-5903-a1c5-d302418cf124",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "nordic",
    "productName": "Nordic Impact Resistant Shingles",
    "productType": "Asphalt Shingle",
    "description": "Premium performance shingles with polymer-modified asphalt for maximum durability. UL 2218 Class 4 impact resistance rating. ArmourZone technology. 130 MPH wind warranty.",
    "productBrand": "IKO",
    "productLine": "Nordic",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.iko.com/na/wp-content/uploads/2024/05/nordic-impact-resistant-shingle.webp",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/iko/nordic"
  },
  {
    "id": "b4590156-db26-5442-b321-8f7663b528de",
    "trade": "Roofing",
    "tier": "Good",
    "productId": "marathon-plus",
    "productName": "Marathon Plus AR 3-Tab Shingles",
    "productType": "Asphalt Shingle",
    "description": "Traditional 3-tab shingles with algae resistance. Affordable and reliable. 60 MPH wind warranty. Entry-level residential roofing.",
    "productBrand": "IKO",
    "productLine": "Marathon Plus AR",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.iko.com/na/wp-content/uploads/2024/05/marathon-plus-ar-shingle.webp",
    "warrantyYears": 25,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: 3-Tab | Wind rating: 60 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/iko/marathon-plus"
  },
  {
    "id": "ad697dcb-dc20-5a69-acc9-8bcdb83a1e2c",
    "trade": "Roofing",
    "tier": "Better",
    "productId": "cambridge-cool-series",
    "productName": "Cambridge Cool Series Shingles",
    "productType": "Asphalt Shingle",
    "description": "Cool roof shingles with solar-reflecting granules for energy efficiency. Available in multiple colors.",
    "productBrand": "IKO",
    "productLine": "Cambridge Cool",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.iko.com/na/wp-content/uploads/2024/05/cambridge-cool-colors-shingle.webp",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/iko/cambridge-cool-series"
  },
  {
    "id": "8e912f0e-979f-5d81-bb05-876addd6e6de",
    "trade": "Roofing",
    "tier": "Good",
    "productId": "landmark",
    "productName": "Landmark Architectural Shingles",
    "productType": "Asphalt Shingle",
    "description": "Dual-layered architectural shingle with dimensional appearance. 21 colors available. 110 MPH wind warranty. Class A fire rating. Industry-leading warranty with SureStart protection.",
    "productBrand": "CertainTeed",
    "productLine": "Landmark",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.certainteed.com/sites/default/files/styles/product_image/public/2023-06/landmark-moire-black-shingle.jpg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 110 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/certainteed/landmark"
  },
  {
    "id": "0e6cff70-1d15-554a-9898-7a19e54c0a10",
    "trade": "Roofing",
    "tier": "Better",
    "productId": "landmark-pro",
    "productName": "Landmark PRO Architectural Shingles",
    "productType": "Asphalt Shingle",
    "description": "Upgraded architectural shingle with 20% more weight than standard Landmark. Max Def color technology for deeper shadow lines. 22 color options. Enhanced durability for harsh climates.",
    "productBrand": "CertainTeed",
    "productLine": "Landmark PRO",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.certainteed.com/sites/default/files/styles/product_image/public/2023-06/landmark-pro-cobblestone-gray.jpg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 110 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/certainteed/landmark-pro"
  },
  {
    "id": "1db09974-f9d7-5471-98d1-4fb5a2184a24",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "presidential-shake",
    "productName": "Presidential Shake Shingles",
    "productType": "Asphalt Shingle",
    "description": "Luxury shingles that replicate the look of hand-split cedar shakes. Triple laminate construction (TL). Random-cut tabs and deep shadow lines. Available with ClimateFlex rubberized technology.",
    "productBrand": "CertainTeed",
    "productLine": "Presidential Shake",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://assets.roofle.com/cer/ps/charcoalblack/certainteed-presidential-shake-charcoal-black-swatch.jpg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Designer | Wind rating: 110 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/certainteed/presidential-shake"
  },
  {
    "id": "08fc1a58-86c9-5034-8ca7-301ad8f71313",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "grand-manor",
    "productName": "Grand Manor Luxury Shingles",
    "productType": "Asphalt Shingle",
    "description": "Ultra-premium luxury shingles replicating natural slate. Random tabs and deep shadow lines for authentic slate appearance. UL Class 4 impact resistance. Class A fire rating. StreakFighter algae resistance.",
    "productBrand": "CertainTeed",
    "productLine": "Grand Manor",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.certainteed.com/sites/default/files/styles/product_image/public/2023-06/grand-manor-canyon-slate.jpg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Designer | Wind rating: 110 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/certainteed/grand-manor"
  },
  {
    "id": "13853fe5-dfb7-513b-928b-126f5755a40b",
    "trade": "Roofing",
    "tier": "Good",
    "productId": "xt-25",
    "productName": "XT 25 3-Tab Shingles",
    "productType": "Asphalt Shingle",
    "description": "Traditional 3-tab shingles providing reliable protection at an affordable price. Basic wind resistance with 25-year limited warranty coverage.",
    "productBrand": "CertainTeed",
    "productLine": "XT 25",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.certainteed.com/sites/default/files/styles/product_image/public/2023-06/xt25-hunter-green.jpg",
    "warrantyYears": 25,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: 3-Tab | Wind rating: 60 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/certainteed/xt-25"
  },
  {
    "id": "15464c93-3bd9-59dc-9985-97bcc7e4e60b",
    "trade": "Roofing",
    "tier": "Better",
    "productId": "landmark-climateflex",
    "productName": "Landmark ClimateFlex Shingles",
    "productType": "Asphalt Shingle",
    "description": "Rubberized asphalt shingle with enhanced flexibility and impact resistance. SBS-modified for superior weather performance in extreme climates.",
    "productBrand": "CertainTeed",
    "productLine": "Landmark ClimateFlex",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.certainteed.com/sites/default/files/styles/product_image/public/2023-06/landmark-climateflex-weathered-wood.jpg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/certainteed/landmark-climateflex"
  },
  {
    "id": "ffb8634b-e489-5a59-b0b3-ec6798b90d1e",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "highland-slate",
    "productName": "Highland Slate Shingles",
    "productType": "Asphalt Shingle",
    "description": "Premium slate-look shingles with realistic texture and color variations. Enhanced durability and dimensional appearance.",
    "productBrand": "CertainTeed",
    "productLine": "Highland Slate",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.certainteed.com/sites/default/files/styles/product_image/public/2023-06/highland-slate-new-england-slate.jpg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Designer | Wind rating: 110 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/certainteed/highland-slate"
  },
  {
    "id": "f2ef7d0b-f664-5c81-beed-211dff6b29dd",
    "trade": "Roofing",
    "tier": "Better",
    "productId": "landmark-solaris",
    "productName": "Landmark Solaris Cool Roof Shingles",
    "productType": "Asphalt Shingle",
    "description": "Cool roof shingles with solar-reflecting granules for energy efficiency and reduced cooling costs. ENERGY STAR® rated options available.",
    "productBrand": "CertainTeed",
    "productLine": "Landmark Solaris",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.certainteed.com/sites/default/files/styles/product_image/public/2023-06/landmark-solaris-silver-birch.jpg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 110 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/certainteed/landmark-solaris"
  },
  {
    "id": "38fd5275-379d-5d0d-ad9c-19eba03e482d",
    "trade": "Roofing",
    "tier": "Better",
    "productId": "landmark-premium",
    "productName": "Landmark Premium Shingles",
    "productType": "Asphalt Shingle",
    "description": "Heavier-weight version of Landmark with enhanced dimensional appearance and durability. Max Def colors available.",
    "productBrand": "CertainTeed",
    "productLine": "Landmark Premium",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.certainteed.com/sites/default/files/styles/product_image/public/2023-06/landmark-premium-weathered-wood.jpg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 110 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/certainteed/landmark-premium"
  },
  {
    "id": "fd27f369-d7c3-5335-b8ec-a3196d703246",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "carriage-house",
    "productName": "Carriage House Shingles",
    "productType": "Asphalt Shingle",
    "description": "Premium architectural shingles with distinctive scalloped edge design. Old-world European charm with modern performance.",
    "productBrand": "CertainTeed",
    "productLine": "Carriage House",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.certainteed.com/sites/default/files/styles/product_image/public/2023-06/carriage-house-sable-black.jpg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Designer | Wind rating: 110 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/certainteed/carriage-house"
  },
  {
    "id": "0d1ed5a5-cd7c-567a-8fd1-8b76ed23e1d2",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "belmont-ir",
    "productName": "Belmont IR Shingles",
    "productType": "Asphalt Shingle",
    "description": "Class 4 impact-resistant luxury shingles with rubberized asphalt construction. Enhanced hail and storm protection.",
    "productBrand": "CertainTeed",
    "productLine": "Belmont IR",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.certainteed.com/sites/default/files/styles/product_image/public/2023-06/belmont-ir-slate-gray.jpg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Designer | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/certainteed/belmont-ir"
  },
  {
    "id": "e79ca060-307e-509b-ba79-512a11038d95",
    "trade": "Roofing",
    "tier": "Better",
    "productId": "landmark-ir",
    "productName": "Landmark Impact Resistant Shingles",
    "productType": "Asphalt Shingle",
    "description": "Impact-resistant version of Landmark shingles with UL Class 4 impact rating. Enhanced protection against hail and debris.",
    "productBrand": "CertainTeed",
    "productLine": "Landmark IR",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.certainteed.com/sites/default/files/styles/product_image/public/2023-06/landmark-ir-weathered-wood.jpg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 110 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/certainteed/landmark-ir"
  },
  {
    "id": "8913f715-c003-522d-b2cd-d29affaf7aca",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "arcadia-shake",
    "productName": "Arcadia Shake Shingles",
    "productType": "Asphalt Shingle",
    "description": "Premium synthetic shake shingles with authentic wood appearance. Enhanced durability and low maintenance.",
    "productBrand": "CertainTeed",
    "productLine": "Arcadia Shake",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.certainteed.com/sites/default/files/styles/product_image/public/2023-06/arcadia-shake-cedarwood.jpg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Designer | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/certainteed/arcadia-shake"
  },
  {
    "id": "a59dbb2b-17ca-5599-b17e-8bcccf0d55fe",
    "trade": "Roofing",
    "tier": "Better",
    "productId": "coolstar",
    "productName": "CertainTeed CoolStar Shingles",
    "productType": "Asphalt Shingle",
    "description": "Solar-reflecting shingles designed to reduce roof temperature and energy costs. Compliant with cool roof requirements.",
    "productBrand": "CertainTeed",
    "productLine": "CoolStar",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.certainteed.com/sites/default/files/styles/product_image/public/2023-06/coolstar-white.jpg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 110 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/certainteed/coolstar"
  },
  {
    "id": "3a760bec-79f8-58dc-89d0-eb70d539ec54",
    "trade": "Roofing",
    "tier": "Good",
    "productId": "strip",
    "productName": "CertainTeed Strip Shingles",
    "productType": "Asphalt Shingle",
    "description": "Basic 3-tab shingles for budget-conscious projects. Reliable weather protection with standard warranty.",
    "productBrand": "CertainTeed",
    "productLine": "Strip",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.certainteed.com/sites/default/files/styles/product_image/public/2023-06/xt25-hunter-green.jpg",
    "warrantyYears": 25,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: 3-Tab | Wind rating: 60 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/certainteed/strip"
  },
  {
    "id": "8fbadd02-a99a-5c53-b0c0-bf9169024a66",
    "trade": "Roofing",
    "tier": "Better",
    "productId": "pinnacle-pristine",
    "productName": "Pinnacle Pristine Shingles",
    "productType": "Asphalt Shingle",
    "description": "Architectural shingles with 3M Scotchgard Protector for lifetime algae resistance. Class 3 impact resistance. 130 MPH wind warranty. High-definition colors.",
    "productBrand": "Atlas Roofing",
    "productLine": "Pinnacle Pristine",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://assets.roofle.com/atl/sms/majesticshake/atlas-stormmaster-shake-majestic-shake-house-380.jpg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/atlas/pinnacle-pristine"
  },
  {
    "id": "80910c3a-0256-5d88-bfa4-4179fe2f4804",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "stormmaster-shake",
    "productName": "StormMaster Shake Shingles",
    "productType": "Asphalt Shingle",
    "description": "Premium luxury shingles with Class 4 impact resistance (UL 2218). 150 MPH wind warranty. 3M Scotchgard lifetime algae protection. Smog-reducing granules.",
    "productBrand": "Atlas Roofing",
    "productLine": "StormMaster Shake",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://assets.roofle.com/atl/sms/majesticshake/atlas-stormmaster-shake-majestic-shake-house-380.jpg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Designer | Wind rating: 150 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/atlas/stormmaster-shake"
  },
  {
    "id": "a9f23707-7d31-52d0-aea4-16dfbfe3ccba",
    "trade": "Roofing",
    "tier": "Good",
    "productId": "prolam",
    "productName": "ProLam Architectural Shingles",
    "productType": "Asphalt Shingle",
    "description": "Entry-level architectural laminated shingles. Reliable performance with dimensional appearance. Available in popular colors.",
    "productBrand": "Atlas Roofing",
    "productLine": "ProLam",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.atlasroofing.com/sites/default/files/styles/product_image/public/prolam-shingle.jpg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 110 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/atlas/prolam"
  },
  {
    "id": "00fcc7d7-a7bd-5583-8c0c-071284c4bfb7",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "stormmaster-slate",
    "productName": "StormMaster Slate Shingles",
    "productType": "Asphalt Shingle",
    "description": "Premium slate-look shingles with Class 4 impact resistance. 150 MPH wind warranty. Smog-reducing granules.",
    "productBrand": "Atlas Roofing",
    "productLine": "StormMaster Slate",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.atlasroofing.com/sites/default/files/styles/product_image/public/stormmaster-slate.jpg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Designer | Wind rating: 150 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/atlas/stormmaster-slate"
  },
  {
    "id": "5397f21f-215b-5f71-a5c2-88470d886e12",
    "trade": "Roofing",
    "tier": "Good",
    "productId": "glassmaster",
    "productName": "GlassMaster 3-Tab Shingles",
    "productType": "Asphalt Shingle",
    "description": "Traditional 3-tab shingles. Fiberglass-reinforced construction. Budget-friendly with 25-year warranty.",
    "productBrand": "Atlas Roofing",
    "productLine": "GlassMaster",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.atlasroofing.com/sites/default/files/styles/product_image/public/glassmaster-shingle.jpg",
    "warrantyYears": 25,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: 3-Tab | Wind rating: 60 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/atlas/glassmaster"
  },
  {
    "id": "8ba30b5c-f641-56f8-b1da-ed4227d731bb",
    "trade": "Roofing",
    "tier": "Better",
    "productId": "briarwood-pro",
    "productName": "Briarwood Pro Shingles",
    "productType": "Asphalt Shingle",
    "description": "Architectural shingles with enhanced color blending and shadow lines. 130 MPH wind warranty. 3M Scotchgard algae protection.",
    "productBrand": "Atlas Roofing",
    "productLine": "Briarwood Pro",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.atlasroofing.com/sites/default/files/styles/product_image/public/briarwood-pro-shingle.jpg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/atlas/briarwood-pro"
  },
  {
    "id": "71a6249f-2e1f-5314-b67c-0849f9552ad3",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "hp42",
    "productName": "HP42 High Performance Shingles",
    "productType": "Asphalt Shingle",
    "description": "High-performance architectural shingles with 4.5-inch exposure. Fast installation with excellent coverage and wind resistance.",
    "productBrand": "Atlas Roofing",
    "productLine": "HP42",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.atlasroofing.com/sites/default/files/styles/product_image/public/hp42-shingle.jpg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/atlas/hp42"
  },
  {
    "id": "bf18f40d-51e0-5bdb-ab5f-940b282ebcff",
    "trade": "Roofing",
    "tier": "Better",
    "productId": "castlebrook",
    "productName": "Castlebrook Designer Shingles",
    "productType": "Asphalt Shingle",
    "description": "Heavyweight designer shingles with bold shadow lines and rich color dimension. Premium architectural appearance.",
    "productBrand": "Atlas Roofing",
    "productLine": "Castlebrook",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.atlasroofing.com/sites/default/files/styles/product_image/public/castlebrook-shingle.jpg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Designer | Wind rating: 110 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/atlas/castlebrook"
  },
  {
    "id": "a83af5f3-697b-5b6d-9293-6e19a4332a7c",
    "trade": "Roofing",
    "tier": "Better",
    "productId": "highlander-nex",
    "productName": "Highlander NEX Architectural Shingles",
    "productType": "Asphalt Shingle",
    "description": "Polymer-modified architectural shingles with NEX rubberized asphalt for superior all-weather performance. Class 4 impact resistance. 130 MPH wind warranty.",
    "productBrand": "Malarkey",
    "productLine": "Highlander NEX",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://assets.roofle.com/mal/hn/naturalwood/malarkey-highlander-nex-natural-wood-house.jpg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/malarkey/highlander-nex"
  },
  {
    "id": "3a1e9c2f-5d44-5148-b071-09625e80bbc8",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "legacy-nex",
    "productName": "Legacy NEX Designer Shingles",
    "productType": "Asphalt Shingle",
    "description": "Premium designer shingles with Scotchgard algae protection and smog-reducing granules. Class 4 impact resistance. 140 MPH wind warranty.",
    "productBrand": "Malarkey",
    "productLine": "Legacy NEX",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://assets.roofle.com/mal/hn/midnightblack/malarkey-highlander-nex-midnight-black-house.jpg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Designer | Wind rating: 140 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/malarkey/legacy-nex"
  },
  {
    "id": "84d41de7-1dc6-59ba-8fb4-1816dbaf5f13",
    "trade": "Roofing",
    "tier": "Better",
    "productId": "vista-nex",
    "productName": "Vista NEX Architectural Shingles",
    "productType": "Asphalt Shingle",
    "description": "Architectural shingles with enhanced dimensional appearance and SBS-modified rubberized asphalt. Class 4 impact resistance. 130 MPH wind warranty.",
    "productBrand": "Malarkey",
    "productLine": "Vista NEX",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://assets.roofle.com/mal/hn/stormgrey/malarkey-highlander-nex-storm-grey-swatch-380.jpg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/malarkey/vista-nex"
  },
  {
    "id": "badf53b2-2737-53d6-b1c1-6d2e91805d37",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "windsrift-nex",
    "productName": "Windsrift NEX Designer Shingles",
    "productType": "Asphalt Shingle",
    "description": "Designer shingles with unique shingle design and NEX rubberized asphalt. Enhanced aesthetic appeal with superior performance.",
    "productBrand": "Malarkey",
    "productLine": "Windsrift NEX",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://assets.roofle.com/mal/hn/naturalwood/malarkey-highlander-nex-natural-wood-house.jpg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Designer | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/malarkey/windsrift-nex"
  },
  {
    "id": "19efa844-c9af-56aa-a918-aae493dfae9e",
    "trade": "Roofing",
    "tier": "Better",
    "productId": "ecoasis-nex",
    "productName": "Ecoasis NEX Solar Reflective Shingles",
    "productType": "Asphalt Shingle",
    "description": "Solar-reflective shingles with NEX polymer-modified asphalt. Cool roof technology reduces energy costs. ENERGY STAR® rated.",
    "productBrand": "Malarkey",
    "productLine": "Ecoasis NEX",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://assets.roofle.com/mal/hn/stormgrey/malarkey-highlander-nex-storm-grey-swatch-380.jpg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/malarkey/ecoasis-nex"
  },
  {
    "id": "26630910-382b-58ae-800b-22b621951495",
    "trade": "Roofing",
    "tier": "Better",
    "productId": "secure-start",
    "productName": "Secure Start Synthetic Underlayment",
    "productType": "Synthetic",
    "description": "Premium synthetic underlayment for enhanced roof protection. Durable, water-resistant barrier beneath shingles.",
    "productBrand": "Malarkey",
    "productLine": "Secure Start",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://assets.roofle.com/mal/hn/naturalwood/malarkey-highlander-nex-natural-wood-house.jpg",
    "warrantyYears": 0,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Specialty | Wind rating: N/A | Fire rating: N/A | Roofle URL: https://catalog.roofle.com/catalog/malarkey/secure-start"
  },
  {
    "id": "1b75bafa-6322-5554-9582-f884fe2add8c",
    "trade": "Roofing",
    "tier": "Better",
    "productId": "heritage-premium",
    "productName": "Heritage Premium Architectural Shingles",
    "productType": "Asphalt Shingle",
    "description": "Premium architectural shingles with Aged Oak granule blend technology. Enhanced dimensional appearance. 130 MPH wind warranty.",
    "productBrand": "TAMKO",
    "productLine": "Heritage Premium",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://assets.roofle.com/tam/hv/weatheredwood/tamko-heritage-vintage-weathered-wood-house.jpg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/tamko/heritage-premium"
  },
  {
    "id": "ec3695d9-c964-583d-bc94-68bd276ea520",
    "trade": "Roofing",
    "tier": "Good",
    "productId": "heritage",
    "productName": "Heritage Architectural Shingles",
    "productType": "Asphalt Shingle",
    "description": "Architectural shingles with natural wood-shake appearance. Durable fiberglass construction. 110 MPH wind warranty.",
    "productBrand": "TAMKO",
    "productLine": "Heritage",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://assets.roofle.com/tam/hv/weatheredwood/tamko-heritage-vintage-weathered-wood-house.jpg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 110 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/tamko/heritage"
  },
  {
    "id": "41f0b9ba-8de7-5de0-9898-87ec0f741ecc",
    "trade": "Roofing",
    "tier": "Better",
    "productId": "heritage-vintage",
    "productName": "Heritage Vintage Shingles",
    "productType": "Asphalt Shingle",
    "description": "Designer shingles with enhanced color granules for striking curb appeal. Rich color depth and contrast.",
    "productBrand": "TAMKO",
    "productLine": "Heritage Vintage",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://assets.roofle.com/tam/hv/weatheredwood/tamko-heritage-vintage-weathered-wood-swatch.jpg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Designer | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/tamko/heritage-vintage"
  },
  {
    "id": "ff4ce514-2ca4-59d6-8ebf-1bb488960c29",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "titan-xt",
    "productName": "Titan XT StormFighter IR Shingles",
    "productType": "Asphalt Shingle",
    "description": "Class 4 impact-resistant shingles with StormFighter technology. Enhanced wind and hail protection. 130 MPH wind warranty.",
    "productBrand": "TAMKO",
    "productLine": "Titan XT",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.tamko.com/wp-content/uploads/2024/03/titan-xt-shingle.jpg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/tamko/titan-xt"
  },
  {
    "id": "5cb0d74b-620d-56a0-b018-5ff430d94b57",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "titan-ult",
    "productName": "Titan ULT StormFighter IR Shingles",
    "productType": "Asphalt Shingle",
    "description": "Ultra-premium impact-resistant shingles with maximum durability. StormFighter Class 4 impact resistance. 130 MPH wind warranty.",
    "productBrand": "TAMKO",
    "productLine": "Titan ULT",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.tamko.com/wp-content/uploads/2024/03/titan-ult-shingle.jpg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Designer | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/tamko/titan-ult"
  },
  {
    "id": "5e5263c5-1833-5731-8180-fd6588c38ca9",
    "trade": "Roofing",
    "tier": "Good",
    "productId": "elite-glass-seal",
    "productName": "Elite Glass-Seal 3-Tab Shingles",
    "productType": "Asphalt Shingle",
    "description": "Traditional 3-tab shingles with fiberglass reinforcement. 25-year warranty. Cost-effective roofing solution.",
    "productBrand": "TAMKO",
    "productLine": "Elite Glass-Seal",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.tamko.com/wp-content/uploads/2024/03/elite-glass-seal-shingle.jpg",
    "warrantyYears": 25,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: 3-Tab | Wind rating: 60 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/tamko/elite-glass-seal"
  },
  {
    "id": "77726e2d-f4d1-50d1-ab77-7b61afd79464",
    "trade": "Roofing",
    "tier": "Better",
    "productId": "heritage-ir",
    "productName": "Heritage IR Shingles",
    "productType": "Asphalt Shingle",
    "description": "Impact-resistant version of Heritage shingles with UL Class 4 rating. Enhanced protection against hail and severe weather.",
    "productBrand": "TAMKO",
    "productLine": "Heritage IR",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.tamko.com/wp-content/uploads/2024/03/heritage-ir-shingle.jpg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Architectural | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/tamko/heritage-ir"
  },
  {
    "id": "6baa5791-6f87-54af-b5ff-90c685a48893",
    "trade": "Roofing",
    "tier": "Better",
    "productId": "metalworks-stonecrest",
    "productName": "MetalWorks StoneCrest Tile",
    "productType": "Metal",
    "description": "Premium metal roofing tiles with stone-coated steel construction. Lightweight, durable, and fire-resistant.",
    "productBrand": "TAMKO",
    "productLine": "MetalWorks StoneCrest",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.tamko.com/wp-content/uploads/2024/03/metalworks-stonecrest.jpg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Specialty | Wind rating: 120 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/tamko/metalworks-stonecrest"
  },
  {
    "id": "a05b6f27-524f-5745-b117-5ce33333f7aa",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "multi-width-slate",
    "productName": "DaVinci Multi-Width Slate",
    "productType": "Synthetic",
    "description": "Premium composite slate tiles in multiple widths for authentic natural slate appearance. Class 4 impact resistance. Fire resistant. 110 MPH wind rating.",
    "productBrand": "DaVinci Roofscapes",
    "productLine": "Multi-Width Slate",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://static-ng.becn.digital/images/large/C-468493_default_hero.jpg",
    "warrantyYears": 0,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Specialty | Wind rating: 110 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/davinci/multi-width-slate"
  },
  {
    "id": "01286d2a-783f-56b3-82d4-da5683364a7a",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "single-width-slate",
    "productName": "DaVinci Single-Width Slate",
    "productType": "Synthetic",
    "description": "Single-width composite slate tiles for clean, uniform appearance. Class 4 impact resistance. Low maintenance.",
    "productBrand": "DaVinci Roofscapes",
    "productLine": "Single-Width Slate",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://static-ng.becn.digital/images/large/C-468493_default_hero.jpg",
    "warrantyYears": 0,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Specialty | Wind rating: 110 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/davinci/single-width-slate"
  },
  {
    "id": "64eda376-4be7-5981-9780-2cf67b79f761",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "multi-width-shake",
    "productName": "DaVinci Multi-Width Shake",
    "productType": "Synthetic",
    "description": "Premium composite shake tiles with natural wood appearance. Multiple widths for authentic cedar shake look. Class 4 impact resistance.",
    "productBrand": "DaVinci Roofscapes",
    "productLine": "Multi-Width Shake",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.westlakeroyalbuildingproducts.com/sites/default/files/styles/large_16_9/public/2025-04/MWSHBlackOakCO0002.jpg",
    "warrantyYears": 0,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Specialty | Wind rating: 110 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/davinci/multi-width-shake"
  },
  {
    "id": "bf5f73ef-5c78-599e-9fc8-8a65793e2c6d",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "single-width-shake",
    "productName": "DaVinci Single-Width Shake",
    "productType": "Synthetic",
    "description": "Single-width composite shake tiles for uniform cedar shake appearance. Class 4 impact and fire resistant.",
    "productBrand": "DaVinci Roofscapes",
    "productLine": "Single-Width Shake",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.westlakeroyalbuildingproducts.com/sites/default/files/styles/large_16_9/public/2025-04/MWSHBlackOakCO0002.jpg",
    "warrantyYears": 0,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Specialty | Wind rating: 110 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/davinci/single-width-shake"
  },
  {
    "id": "b13e8ea4-0f59-52e8-b84a-03b3a55adbcc",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "bellaforte-slate",
    "productName": "DaVinci Bellaforte Slate",
    "productType": "Synthetic",
    "description": "Self-aligning composite slate tiles with easy installation. Natural slate appearance with superior durability.",
    "productBrand": "DaVinci Roofscapes",
    "productLine": "Bellaforte Slate",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.davinciroofscapes.com/sites/default/files/styles/product_image/public/bellaforte-slate.jpg",
    "warrantyYears": 0,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Specialty | Wind rating: 110 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/davinci/bellaforte-slate"
  },
  {
    "id": "d1afdf22-ade4-5fbe-ac0a-298176404ca3",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "bellaforte-shake",
    "productName": "DaVinci Bellaforte Shake",
    "productType": "Synthetic",
    "description": "Self-aligning composite shake tiles. Natural wood shake appearance with enhanced durability and easy installation.",
    "productBrand": "DaVinci Roofscapes",
    "productLine": "Bellaforte Shake",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.davinciroofscapes.com/sites/default/files/styles/product_image/public/bellaforte-shake.jpg",
    "warrantyYears": 0,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Specialty | Wind rating: 110 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/davinci/bellaforte-shake"
  },
  {
    "id": "b23c92d1-62d3-5c2c-8a92-45851b65ed24",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "fancy-shake",
    "productName": "DaVinci Fancy Shake",
    "productType": "Synthetic",
    "description": "Premium composite shake with hand-split cedar appearance. Rich natural wood texture with superior weather resistance.",
    "productBrand": "DaVinci Roofscapes",
    "productLine": "Fancy Shake",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.davinciroofscapes.com/sites/default/files/styles/product_image/public/fancy-shake.jpg",
    "warrantyYears": 0,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Specialty | Wind rating: 110 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/davinci/fancy-shake"
  },
  {
    "id": "cf86c4ea-7e9f-5776-9b01-2b6440998047",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "hand-split-shake",
    "productName": "DaVinci Hand-Split Shake",
    "productType": "Synthetic",
    "description": "Hand-split appearance composite shake tiles for rustic, natural wood look. Class 4 impact and fire resistant.",
    "productBrand": "DaVinci Roofscapes",
    "productLine": "Hand-Split Shake",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.davinciroofscapes.com/sites/default/files/styles/product_image/public/hand-split-shake.jpg",
    "warrantyYears": 0,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Specialty | Wind rating: 110 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/davinci/hand-split-shake"
  },
  {
    "id": "61a6e1d2-5f96-5755-b184-657a0caa56c2",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "smooth-slate",
    "productName": "DaVinci Smooth Slate",
    "productType": "Synthetic",
    "description": "Smooth-finish composite slate tiles. Clean, contemporary appearance with natural slate aesthetics.",
    "productBrand": "DaVinci Roofscapes",
    "productLine": "Smooth Slate",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.davinciroofscapes.com/sites/default/files/styles/product_image/public/smooth-slate.jpg",
    "warrantyYears": 0,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Specialty | Wind rating: 110 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/davinci/smooth-slate"
  },
  {
    "id": "f77fe03e-d2a4-5ba2-a48e-48ea683dd73e",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "vermont-slate",
    "productName": "Euroshield Vermont Slate",
    "productType": "Synthetic",
    "description": "Premium rubber slate tiles made from recycled materials. Authentic slate appearance with superior hail resistance. Class 4 impact rated.",
    "productBrand": "Euroshield",
    "productLine": "Vermont Slate",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://lirp.cdn-website.com/1232c3b1/dms3rep/multi/opt/euroshield+slate+rubber+shingles-432w.jpg",
    "warrantyYears": 0,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Specialty | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/euroshield/vermont-slate"
  },
  {
    "id": "f1472b7d-d1ef-5a6c-a213-8da20a7ca63f",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "rundle-slate",
    "productName": "Euroshield Rundle Slate",
    "productType": "Synthetic",
    "description": "Premium rubber slate with natural stone texture. Made from recycled rubber for extreme durability and hail resistance.",
    "productBrand": "Euroshield",
    "productLine": "Rundle Slate",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://lirp.cdn-website.com/1232c3b1/dms3rep/multi/opt/Rundle-Slate-Gallery2-640w.jpg",
    "warrantyYears": 0,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Specialty | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/euroshield/rundle-slate"
  },
  {
    "id": "f5713f09-1867-59ce-bb6f-7bf4a4615740",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "harvest-shake",
    "productName": "Euroshield Harvest Shake",
    "productType": "Synthetic",
    "description": "Premium rubber shake tiles with natural cedar appearance. Made from recycled materials. Superior impact and weather resistance.",
    "productBrand": "Euroshield",
    "productLine": "Harvest Shake",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://lirp.cdn-website.com/1232c3b1/dms3rep/multi/opt/euroshield+slate+rubber+shingles-432w.jpg",
    "warrantyYears": 0,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Specialty | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/euroshield/harvest-shake"
  },
  {
    "id": "191a08ff-a7c3-5a50-8e62-eeb08bb5104d",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "ranchlands-shake",
    "productName": "Euroshield Ranchlands Shake",
    "productType": "Synthetic",
    "description": "Hand-split cedar-look rubber shake tiles. Extreme durability with authentic rustic wood appearance.",
    "productBrand": "Euroshield",
    "productLine": "Ranchlands Shake",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://lirp.cdn-website.com/1232c3b1/dms3rep/multi/opt/euroshield+slate+rubber+shingles-432w.jpg",
    "warrantyYears": 0,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Specialty | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/euroshield/ranchlands-shake"
  },
  {
    "id": "3fbe3d7b-b83b-5921-9505-97c640c0326b",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "new-cedar-shake",
    "productName": "Euroshield New Cedar Shake",
    "productType": "Synthetic",
    "description": "New-cut cedar-look rubber shake tiles. Clean, fresh wood appearance with superior hail and impact resistance.",
    "productBrand": "Euroshield",
    "productLine": "New Cedar Shake",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://lirp.cdn-website.com/1232c3b1/dms3rep/multi/opt/euroshield+slate+rubber+shingles-432w.jpg",
    "warrantyYears": 0,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Specialty | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/euroshield/new-cedar-shake"
  },
  {
    "id": "e65d8054-05d1-5854-9a76-69af9b44ff5c",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "old-world-slate",
    "productName": "Brava Old World Slate",
    "productType": "Synthetic",
    "description": "Premium composite slate tiles with authentic Old World European appearance. Class 4 impact and fire resistant. 110 MPH wind rating.",
    "productBrand": "Brava",
    "productLine": "Old World Slate",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.bravarooftile.com/wp-content/uploads/2024/03/old-world-slate.jpg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Specialty | Wind rating: 110 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/brava/old-world-slate"
  },
  {
    "id": "08fbe02d-4aa5-5027-b02c-041bc4c8d394",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "cedar-shake",
    "productName": "Brava Cedar Shake",
    "productType": "Synthetic",
    "description": "Premium composite cedar shake tiles with natural wood grain texture. Available in multiple widths and colors.",
    "productBrand": "Brava",
    "productLine": "Cedar Shake",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.bravarooftile.com/wp-content/uploads/2024/03/cedar-shake.jpg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Specialty | Wind rating: 110 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/brava/cedar-shake"
  },
  {
    "id": "30eeba22-22a6-5797-9694-dd71c8031f33",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "spanish-barrel-tile",
    "productName": "Brava Spanish Barrel Tile",
    "productType": "Synthetic",
    "description": "Premium composite Spanish barrel tiles for Mediterranean and Spanish Colonial architecture. Authentic clay tile appearance.",
    "productBrand": "Brava",
    "productLine": "Spanish Barrel Tile",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://www.bravarooftile.com/wp-content/uploads/2024/03/spanish-barrel-tile.jpg",
    "warrantyYears": 50,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Specialty | Wind rating: 110 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/brava/spanish-barrel-tile"
  },
  {
    "id": "0fa01e29-72b3-592b-8160-b7aa5352d4f2",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "revia-slate",
    "productName": "F-Wave Revia Slate",
    "productType": "Synthetic",
    "description": "Premium synthetic slate shingles with authentic appearance. Class 4 impact resistance. 130 MPH wind warranty. Limited lifetime warranty.",
    "productBrand": "F-Wave",
    "productLine": "Revia Slate",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://fwave.com/wp-content/uploads/2024/03/revia-slate.jpg",
    "warrantyYears": 0,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Specialty | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/f-wave/revia-slate"
  },
  {
    "id": "c738c3e2-50ba-54d5-8588-736a9dcbd367",
    "trade": "Roofing",
    "tier": "Best",
    "productId": "revia-shake",
    "productName": "F-Wave Revia Shake",
    "productType": "Synthetic",
    "description": "Premium synthetic shake shingles with natural cedar appearance. Class 4 impact resistance. 130 MPH wind warranty. Stain-resistant technology.",
    "productBrand": "F-Wave",
    "productLine": "Revia Shake",
    "colorName": "",
    "colorHex": "",
    "imageUrl": "https://fwave.com/wp-content/uploads/2024/03/revia-shake.jpg",
    "warrantyYears": 0,
    "unitCost": 0,
    "laborCost": 0,
    "defaultMargin": 0,
    "defaultMarkup": 0,
    "isActive": true,
    "notes": "Grade: Specialty | Wind rating: 130 | Fire rating: Class A | Roofle URL: https://catalog.roofle.com/catalog/f-wave/revia-shake"
  }
] satisfies TierProduct[];
