export {
  calculateProjectPricing,
  defaultSettings,
  formatMargin,
  formatMoney,
  getExpirationLabel,
  computeNextProposalNumber,
  getTotalCost,
  getTodayLabel,
  initialContacts,
  initialProjects,
  projectSizeOptions,
  riskLevelOptions,
  stateOptions,
  storageKeys,
  statusOptions,
  tradeOptions,
  TYPICAL_COSTS,
  type Contact,
  type AppSettings,
  type CostBreakdown,
  type PriceOptionName,
  type PricingResult,
  type Project,
  type ProjectSize,
  type ProjectState,
  type ProjectStatus,
  type Quote,
  type RiskLevel,
  type ScopeTemplate,
  type Trade,
} from "./app-data";
