export {
  calculateProjectPricing,
  formatMargin,
  formatMoney,
  getExpirationLabel,
  getNextProposalNumber,
  getTotalCost,
  getTodayLabel,
  projectSizeOptions,
  riskLevelOptions,
  stateOptions,
  storageKeys,
  statusOptions,
  tradeOptions,
  TYPICAL_COSTS,
  type Contact,
  type CostBreakdown,
  type PriceOptionName,
  type PricingResult,
  type Project,
  type ProjectSize,
  type ProjectState,
  type ProjectStatus,
  type Quote,
  type RiskLevel,
  type ScopeTemplate,
  type Trade,
} from "./app-data";
